services:
  postgres:
    container_name: payments-postgres
    image: postgres:17
    env_file: apps/payments-api/.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - payments-network

  redis:
    container_name: payments-redis
    image: redis:7
    env_file: apps/payments-api/.env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - payments-dev-redis-data:/redis-data
    networks:
      - payments-network

networks:
  payments-network:
    driver: bridge

volumes:
  postgres-data:
  payments-dev-redis-data:
